### PR TITLE
I added a tiny home icon

### PR DESCRIPTION
**Pull request by Fuhaustin**
I added a home icon

### CODE REVIEW

**Comment by kefeh** [comment]
thanks Austin

**Comment by Fuhaustin** [comment]
Kefeh  how do you do? if you see this message please reply me

**Comment by kefeh** [comment]
Hello austin

**Comment by Fuhaustin** [comment]
Why have you gone so silent  now.

**Comment by kefeh** [comment]
hey austin,

        am sorry i was kind of busy but am back now i guess i will continue
as from tomorrow

Regards
Kefeh

**Comment by Fuhaustin** [comment]
okay i think you can use the wordpress tools to define the structures of
how the site should be, the dashboard,individual profile account i that is
just the structure i can then start the server side programming i see that
you don't have time.
Please define the discussion section, raw css will consume a lot of time.

**Pull request merged**
